project_id = "iipxwwrzkdkestikxcpg"

[functions.translate]
verify_jwt = false

[functions.generate-seo-blogs]
verify_jwt = false

[functions.chatbot]
verify_jwt = false

[functions.send-campaign-emails]
verify_jwt = false

[functions.send-seo-prompts-email]
verify_jwt = false
